### ISSUE TITLE
why the speed of ELSED in my computer is not so fast?

### ISSUE THREAD

**Issue by fightmoney** [iago-suarez/ELSED#5]
Hi!
Your code is great !
But when I use it on my computer(intel i5-11400H Ubuntu 18.04), the speed of ELSED is about 14ms and LSD(OpenCV) is about 19ms. 
It is not so fast in your paper. what is wrong with my computer? I just use your code to test.
I hope to get your reply.
Thanks!!!!!

**Comment by iago-suarez** [comment]
Hi,

Thanks for your interest. The execution times may vary depending on the computer and the image size. The numbers we provided in the paper are the average execution time for images of 640x480 pixels. Note that a cheap mobile phone like the Samsung J5 (Exynox) takes 45.84 ms per image.

- Are you compiling in [Release mode](https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html)? To ensure this, you can add the following argument to CMake:

```
cmake -DCMAKE_BUILD_TYPE=Release ..
```

Also, please consider that OpenCV LSD is not [the original version](http://www.ipol.im/pub/art/2012/gjmr-lsd/). In my experience, the OpenCV version provides worse line detection results.

**Comment by fightmoney** [comment]
Thanks, it work!!!!
Your work has ushered in a new era of line segment detection.
