### ISSUE TITLE
Some  problem when computeGradients

### ISSUE THREAD

**Issue by David-dotcom666** [iago-suarez/ELSED#6]
Hi iago:
first of all, thank you for your OPEN SOURCE.
I am tring to use it in my project.but when i test it, i meet some strange problem(detect some lines that shouldn’t be exist). and finally,i add a imwrite here:

		dstInfo->gImgWO = cv::Mat:(srcImg.size(), dstInfo->dxImg.type());
		dstInfo->gImg = cv::Mat:(srcImg.size(), dstInfo->dxImg.type());
		dstInfo->dirImg = cv::Mat:(srcImg.size(), CV_8UC1);
                cv::imwrite("beforegImg.jpg ", dstInfo->gImg);
and then i find sometimes it will creat a img that is not a "black" one, some "white" pixels on it.
but when i use  cv::Mat::zeros instead of cv::Mat,i test many times and did't meet that again. but i can not sure this. could you help to confirm that?
Thanks.
![tt1](https://user-images.githubusercontent.com/84842493/172543068-494f2d02-8b78-4d2e-a751-b3affc8e6ead.jpg)
![beforegImg](https://user-images.githubusercontent.com/84842493/172543129-dbc55f14-0f22-46c8-900a-588d098e27e7.jpg)

**Comment by iago-suarez** [comment]
Hi,

Sorry for late reply. Could you provide a full example where these lines appear?

I have tested with a pure black image and no lines are detected.

Best,
Iago.

**Comment by David-dotcom666** [comment]
Hi.
It's ok if using your original code to test a  pure black image.because you assign a value to every pixel of **gradient picture**. i meet this problem,bacause i change it and add some conditions to choice the direction of X and Y(to detect the line that is from black to white or from white to black) when calculate GD .so if i didn't use mat:zeros to instead of mat(random init). i make some ‘white’ pixel with cv::mat and never assign a value.
It's not a ”issue“.

thanks for you reply.
BR
David

**Comment by David-dotcom666** [comment]
Hi.
It's ok if using your original code to test a  pure black image.because you assign a value to every pixel of **gradient picture**. i meet this problem,bacause i change it and add some conditions to choice the direction of X and Y(to detect the line that is from black to white or from white to black) when calculate GD .so if i didn't use mat:zeros to instead of mat(random init). i make some ‘white’ pixel with cv::mat and never assign a value.
It's not a ”issue“.

thanks for you reply.
BR
David

**Comment by iago-suarez** [comment]
I see. Could you please provide me with the code where you have changed the direction of X and Y? Or with your gradient picture? If so, I will try to execute it and check if I can find the problem there.

If you give a bit more of context of what you are trying to do, perhaps I can help you as well.

Best,
Iago.
