### ISSUE TITLE
Some features about `ELSED::detectEdges()` ?

### ISSUE THREAD

**Issue by zhangshaos** [iago-suarez/ELSED#7]
Thanks for your nice work!
I use `ELSED::detectEdges()` like:
```cpp
upm::ELSED lineDetector;
auto edges = lineDetector.detectEdges(colorImg);
for (const auto &e: edges) {
    if (e.size() < 2)
      continue;
    const auto &startPx = e.front(), &endPx = e.back();
    // ......
}
```
But, I find `e.back()` seems not a end point of a edge!
What `e` actually means as a vector?

**Comment by iago-suarez** [comment]
Hii, thanks for your interest! 

They should be the first and last pixels of each edge. I encourage you to try the following code:

```c++
  upm::ELSED lineDetector;
  auto edges = lineDetector.detectEdges(img);
  for (const auto &e : edges) {
    if (e.size() < 2)
      continue;
    for (const upm::Pixel &px : e) {
      img.at<cv::Vec3b>(px.y, px.x) = cv::Vec3b(0, 255, 0);
      cv::imshow("Edges", img);
      cv::waitKey(30);
    }
  }
```
If I execute it, it progressively draws all the edges on the image:
![image](https://user-images.githubusercontent.com/7408877/206554161-6332e7ad-b794-414b-a599-9347f89ada0e.png)
