### ISSUE TITLE
Documentation on parameters of the python function

### ISSUE THREAD

**Issue by ogencoglu** [iago-suarez/ELSED#9]
Thanks for the great work. Where can I find what are the parameters of `pyelsed.detect()` and their meanings?

**Comment by iago-suarez** [comment]
Hi, thanks for your interest. The parameters are defined here:

https://github.com/iago-suarez/ELSED/blame/main/src/PYAPI.cpp#L61-L69

They directly expose the parameters of the class ELSEDParams:

https://github.com/iago-suarez/ELSED/blob/main/src/ELSED.h#L11-L47.

If you want to see a more verbose and complete explanation, ultimately you can check the original ELSED paper: 

https://www.sciencedirect.com/science/article/pii/S0031320322001005?fr=RR-9&ref=pdf_download&rr=7ea18800187b384b

I hope this info can help you 😊

**Comment by ogencoglu** [comment]
Thanks a lot!
